"""Token-cost scope gating for snapshot / whole-repo reviews.

Why this exists
---------------
For a normal git PR, Gito only tokenizes the changed diff hunks, so the LLM
bill is already small. For a *snapshot* (a non-git folder reviewed from a
managed snapshot) or a full-codebase ``--all`` review, every file reads as an
added file and Gito sends each file's **entire content** to the model, one
prompt per file (see ``gito/core.py`` ``review()`` -> ``input_is_diff``). That
is the case that explodes on a 10,000-line project.

This module trims that case *without touching accuracy*: it identifies files
that carry no reviewable value for the LLM -- vendored dependencies, generated
code, minified bundles, lockfiles, and data blobs -- and asks Gito to exclude
them from the LLM pass. Ordinary source files are never excluded, so the model
still sees every line a human reviewer would care about.

How it stays "pristine"
-----------------------
Gito already loads an extra project config from ``GITO_EXTRA_PROJECT_CONFIG``
(CodePulse points that at ``review_profile.toml``). Rather than editing any Gito
code, the gate writes a *per-run* copy of that profile whose ``exclude_files``
list is the profile's static baseline plus the computed noise paths, and points
``GITO_EXTRA_PROJECT_CONFIG`` at the copy. Gito's own ``exclude_files`` filter
(applied before tokenization) does the rest.

The deterministic engines (static / taint / cross-file / dependency) still scan
every file in-process, so excluded files keep their non-LLM coverage.

Everything here is stdlib only (``ast`` is not even needed -- classification is
path- and content-marker based).
"""
from __future__ import annotations

import fnmatch
import logging
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

from . import snapshot

logger = logging.getLogger("codepulse.scope_gate")

# Rough bytes-per-token for cost estimates. We deliberately avoid importing a
# tokenizer here (the server process has no LLM env configured); ~4 bytes/token
# is the standard back-of-envelope figure and is only ever shown as "~".
BYTES_PER_TOKEN = 4

# How much of a file we read to sniff for a "generated" marker.
MARKER_SNIFF_BYTES = 4096

# Extremely long-line, low-newline text files are almost always minified or a
# serialized blob even without a ``.min`` in the name.
BLOB_MIN_BYTES = 200_000
BLOB_BYTES_PER_NEWLINE = 500

# Source-like extensions we bother sniffing for generated-code markers.
SOURCE_SUFFIXES = frozenset(
    {
        ".py", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs",
        ".go", ".java", ".kt", ".rb", ".cs", ".php", ".swift",
        ".rs", ".scala", ".c", ".cc", ".cpp", ".h", ".hpp", ".m",
    }
)

# High-precision "this file is machine-written" markers (checked case-insensitively).
GENERATED_MARKERS = (
    "@generated",
    "do not edit",
    "code generated by",
    "autogenerated",
    "auto-generated",
    "automatically generated",
    "generated by protoc",
    "this is an automatically generated file",
)

# (glob, reason) noise patterns matched against the repo-relative POSIX path.
# Kept deliberately conservative: only non-source artifacts. Config files
# (*.json / *.yaml / *.toml) are intentionally NOT here -- they can carry real
# security/logic signal, so the LLM keeps reviewing them.
_NOISE_GLOBS: tuple[tuple[str, str], ...] = (
    # Vendored dependencies.
    ("node_modules/", "vendored"),
    ("bower_components/", "vendored"),
    ("vendor/", "vendored"),
    ("third_party/", "vendored"),
    ("site-packages/", "vendored"),
    (".venv/", "vendored"),
    ("venv/", "vendored"),
    # Build / generated output directories.
    ("dist/", "build-output"),
    ("build/", "build-output"),
    ("out/", "build-output"),
    (".next/", "build-output"),
    ("__pycache__/", "build-output"),
    ("coverage/", "build-output"),
    # Minified bundles and source maps.
    ("*.min.js", "minified"),
    ("*.min.css", "minified"),
    ("*.min.mjs", "minified"),
    ("*.bundle.js", "minified"),
    ("*.map", "source-map"),
    # Generated code by naming convention.
    ("*_pb2.py", "generated-code"),
    ("*_pb2_grpc.py", "generated-code"),
    ("*.pb.go", "generated-code"),
    ("*.gen.go", "generated-code"),
    ("*.g.dart", "generated-code"),
    ("*.generated.*", "generated-code"),
    # Lockfiles (some overlap the profile baseline; dedup handles it).
    ("package-lock.json", "lockfile"),
    ("yarn.lock", "lockfile"),
    ("pnpm-lock.yaml", "lockfile"),
    ("poetry.lock", "lockfile"),
    ("Pipfile.lock", "lockfile"),
    ("Cargo.lock", "lockfile"),
    ("composer.lock", "lockfile"),
    ("Gemfile.lock", "lockfile"),
    ("go.sum", "lockfile"),
    # Non-source data blobs the model cannot meaningfully review.
    ("*.svg", "data-asset"),
    ("*.csv", "data-asset"),
    ("*.tsv", "data-asset"),
    ("*.ndjson", "data-asset"),
    ("*.geojson", "data-asset"),
    ("*.parquet", "data-asset"),
    ("*.ipynb", "data-asset"),
    ("*.po", "data-asset"),
    ("*.pot", "data-asset"),
    ("*.mo", "data-asset"),
)


@dataclass
class GatePlan:
    """The outcome of classifying a review's files for LLM scope."""

    excluded: list[dict[str, Any]] = field(default_factory=list)
    kept_count: int = 0
    est_tokens_saved: int = 0

    def exclude_paths(self) -> list[str]:
        return [entry["path"] for entry in self.excluded]

    def reason_counts(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for entry in self.excluded:
            counts[entry["reason"]] = counts.get(entry["reason"], 0) + 1
        return counts

    def to_meta(self, *, sample_limit: int = 300) -> dict[str, Any]:
        """Compact, JSON-serializable summary for the run meta / UI."""
        return {
            "enabled": True,
            "excluded_count": len(self.excluded),
            "kept_count": self.kept_count,
            "est_tokens_saved": self.est_tokens_saved,
            "reasons": self.reason_counts(),
            "excluded": self.excluded[:sample_limit],
            "truncated": len(self.excluded) > sample_limit,
        }


def _posix(path: str) -> str:
    return path.replace("\\", "/")


def _matches_noise(rel_path: str) -> str | None:
    """Return the reason a path is noise, or ``None`` if it looks like source."""
    posix = _posix(rel_path)
    name = posix.rsplit("/", 1)[-1]
    for glob, reason in _NOISE_GLOBS:
        if glob.endswith("/"):
            # Directory marker: match at the root or anywhere in the tree.
            seg = glob[:-1]
            if posix == seg or posix.startswith(seg + "/") or ("/" + seg + "/") in posix:
                return reason
        elif fnmatch.fnmatch(name, glob) or fnmatch.fnmatch(posix, glob):
            return reason
    return None


def _content_reason(abs_path: Path) -> str | None:
    """Sniff a file's head for a generated marker or a minified-blob shape."""
    try:
        raw = abs_path.read_bytes()
    except OSError:
        return None
    head = raw[:MARKER_SNIFF_BYTES]
    suffix = abs_path.suffix.lower()
    if suffix in SOURCE_SUFFIXES:
        try:
            text = head.decode("utf-8", errors="ignore").lower()
        except Exception:  # noqa: BLE001 - defensive; decode shouldn't raise here
            text = ""
        if any(marker in text for marker in GENERATED_MARKERS):
            return "generated-marker"
    # Big file with almost no line breaks -> minified/serialized blob.
    if len(raw) >= BLOB_MIN_BYTES:
        newlines = raw.count(b"\n") or 1
        if len(raw) / newlines >= BLOB_BYTES_PER_NEWLINE:
            return "minified-blob"
    return None


def plan_exclusions(repo_path: Path, files: Iterable[str]) -> GatePlan:
    """Classify ``files`` (repo-relative) into keep vs. exclude-from-LLM.

    Only clearly non-source noise is excluded. Files that don't exist on disk
    are treated as keep (fail open -- never hide a real file from the model).
    """
    plan = GatePlan()
    kept = 0
    for rel in files:
        rel = (rel or "").strip()
        if not rel:
            continue
        reason = _matches_noise(rel)
        abs_path = repo_path / rel
        size = 0
        try:
            size = abs_path.stat().st_size
        except OSError:
            # No file on disk -> we can't be sure it's noise; keep it.
            if reason is None:
                kept += 1
                continue
        if reason is None:
            reason = _content_reason(abs_path)
        if reason is None:
            kept += 1
            continue
        est_tokens = max(1, size // BYTES_PER_TOKEN)
        plan.excluded.append(
            {"path": _posix(rel), "reason": reason, "bytes": size, "est_tokens": est_tokens}
        )
        plan.est_tokens_saved += est_tokens
    plan.kept_count = kept
    return plan


def should_gate(payload: dict[str, Any], options: dict[str, Any]) -> bool:
    """Auto-on for snapshot / whole-repo reviews; opt-out via ``scopeGate: false``.

    A normal git PR (modified files) is left untouched -- Gito already only
    tokenizes its diff hunks there, so gating buys nothing.
    """
    if payload.get("scopeGate") is False:
        return False
    return options.get("mode") == "all" or options.get("refs") == snapshot.SNAPSHOT_REFS


def _render_string_array(key: str, values: list[str]) -> str:
    """Emit a TOML array-of-strings assignment with correct escaping."""
    lines = [f"{key} = ["]
    for value in values:
        escaped = (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\t", "\\t")
        )
        lines.append(f'    "{escaped}",')
    lines.append("]")
    return "\n".join(lines)


def _replace_exclude_files(base_text: str, merged: list[str]) -> str:
    """Return ``base_text`` with its ``exclude_files = [...]`` block replaced.

    The array contains only string literals (no nested brackets), so the first
    ``]`` after the key closes it. If the base has no ``exclude_files`` key, the
    new block is prepended at the very top (a bare top-level key, valid TOML).
    """
    new_block = _render_string_array("exclude_files", merged)
    start = base_text.find("exclude_files")
    if start == -1:
        return new_block + "\n\n" + base_text
    open_bracket = base_text.find("[", start)
    close_bracket = base_text.find("]", open_bracket)
    if open_bracket == -1 or close_bracket == -1:
        return new_block + "\n\n" + base_text
    return base_text[:start] + new_block + base_text[close_bracket + 1:]


def write_run_profile(base_profile: Path, run_dir: Path, extra_excludes: list[str]) -> Path:
    """Write a per-run Gito profile = base profile + extra ``exclude_files``.

    Preserves everything else in the base profile (prompt, pipeline steps,
    ``max_code_tokens``) so the deep-review behavior is unchanged.
    """
    base_text = base_profile.read_text(encoding="utf-8")
    try:
        base_conf = tomllib.loads(base_text)
    except tomllib.TOMLDecodeError:
        logger.warning("Base profile %s is not valid TOML; skipping merge", base_profile)
        base_conf = {}
    base_excludes = [str(x) for x in (base_conf.get("exclude_files") or [])]
    merged = list(base_excludes)
    for extra in extra_excludes:
        if extra not in merged:
            merged.append(extra)
    out_text = _replace_exclude_files(base_text, merged)
    run_dir.mkdir(parents=True, exist_ok=True)
    out_path = run_dir / "review_profile.run.toml"
    out_path.write_text(out_text, encoding="utf-8")
    return out_path
