"""Token-cost scope gating for snapshot / whole-repo reviews."""
from __future__ import annotations

import tomllib
from pathlib import Path

from codepulse_app import scope_gate, snapshot


# --- classification -----------------------------------------------------

def test_noise_globs_match_vendored_generated_and_lockfiles():
    m = scope_gate._matches_noise
    assert m("frontend/node_modules/react/index.js") == "vendored"
    assert m("vendor/pkg/mod.go") == "vendored"
    assert m("app/static/app.min.js") == "minified"
    assert m("api/pb/user_pb2.py") == "generated-code"
    assert m("package-lock.json") == "lockfile"
    assert m("data/exports.csv") == "data-asset"
    assert m("dist/bundle.js") == "build-output"


def test_source_and_config_are_not_noise():
    m = scope_gate._matches_noise
    # Ordinary source keeps its LLM coverage.
    assert m("codepulse_app/server.py") is None
    assert m("src/routes/handler.ts") is None
    # Config files can carry real signal -> never gated by pattern.
    assert m("config/settings.json") is None
    assert m("deploy/k8s.yaml") is None
    assert m("pyproject.toml") is None


def test_vendored_dir_matches_at_root_and_nested():
    m = scope_gate._matches_noise
    assert m("node_modules/left-pad/index.js") == "vendored"
    assert m("a/b/node_modules/x.js") == "vendored"
    # A file merely *named* like the marker is not a directory match.
    assert m("src/node_modules_helper.py") is None


# --- plan_exclusions ----------------------------------------------------

def _write(root: Path, rel: str, content: str = "x = 1\n") -> None:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def test_plan_excludes_noise_keeps_source(tmp_path):
    _write(tmp_path, "app/server.py")
    _write(tmp_path, "app/utils.py")
    _write(tmp_path, "node_modules/dep/index.js")
    _write(tmp_path, "static/app.min.js", "a" * 5000)
    _write(tmp_path, "yarn.lock", "lockfile\n")

    files = ["app/server.py", "app/utils.py", "node_modules/dep/index.js",
             "static/app.min.js", "yarn.lock"]
    plan = scope_gate.plan_exclusions(tmp_path, files)

    excluded = {e["path"] for e in plan.excluded}
    assert excluded == {"node_modules/dep/index.js", "static/app.min.js", "yarn.lock"}
    assert plan.kept_count == 2
    assert plan.est_tokens_saved > 0


def test_plan_sniffs_generated_marker_in_source(tmp_path):
    _write(
        tmp_path,
        "api/schema.py",
        "# @generated by codegen -- DO NOT EDIT\nclass Schema:\n    pass\n",
    )
    plan = scope_gate.plan_exclusions(tmp_path, ["api/schema.py"])
    assert [e["reason"] for e in plan.excluded] == ["generated-marker"]
    assert plan.kept_count == 0


def test_plan_flags_large_low_newline_blob(tmp_path):
    # 300 KB with a single newline -> minified/serialized blob.
    _write(tmp_path, "assets/data.txt", "z" * 300_000 + "\n")
    plan = scope_gate.plan_exclusions(tmp_path, ["assets/data.txt"])
    assert [e["reason"] for e in plan.excluded] == ["minified-blob"]


def test_plan_keeps_normal_source_with_markers_absent(tmp_path):
    _write(tmp_path, "svc/pay.py", "def charge(amount):\n    return amount * 2\n")
    plan = scope_gate.plan_exclusions(tmp_path, ["svc/pay.py"])
    assert plan.excluded == []
    assert plan.kept_count == 1


def test_plan_missing_file_is_kept_not_hidden(tmp_path):
    # A path we can't stat (deleted, or outside the tree) must never be excluded.
    plan = scope_gate.plan_exclusions(tmp_path, ["ghost/only_source.py"])
    assert plan.excluded == []
    assert plan.kept_count == 1


def test_plan_meta_is_compact_and_serializable(tmp_path):
    _write(tmp_path, "yarn.lock", "lock\n")
    plan = scope_gate.plan_exclusions(tmp_path, ["yarn.lock"])
    meta = plan.to_meta()
    assert meta["enabled"] is True
    assert meta["excluded_count"] == 1
    assert meta["reasons"] == {"lockfile": 1}
    import json

    json.dumps(meta)  # must be JSON-serializable


# --- should_gate --------------------------------------------------------

def test_should_gate_on_for_snapshot_and_all():
    assert scope_gate.should_gate({}, {"mode": "refs", "refs": snapshot.SNAPSHOT_REFS})
    assert scope_gate.should_gate({}, {"mode": "all", "refs": ""})


def test_should_gate_off_for_normal_pr():
    assert not scope_gate.should_gate({}, {"mode": "working", "refs": ""})
    assert not scope_gate.should_gate({}, {"mode": "refs", "refs": "main..HEAD"})


def test_should_gate_respects_opt_out():
    opts = {"mode": "all", "refs": ""}
    assert not scope_gate.should_gate({"scopeGate": False}, opts)


# --- write_run_profile --------------------------------------------------

def _base_profile(tmp_path: Path) -> Path:
    path = tmp_path / "review_profile.toml"
    path.write_text(
        'exclude_files = [\n    "yarn.lock",\n    "*.min.js",\n]\n\n'
        "max_code_tokens = 24000\n\n"
        '[prompt_vars]\n'
        'self_id = """\nYou are CodePulse.\n"""\n',
        encoding="utf-8",
    )
    return path


def test_write_run_profile_merges_and_preserves(tmp_path):
    base = _base_profile(tmp_path)
    run_dir = tmp_path / "run"
    out = scope_gate.write_run_profile(base, run_dir, ["node_modules/x.js", "yarn.lock"])

    conf = tomllib.loads(out.read_text(encoding="utf-8"))
    # Base entries preserved, new entry added, no duplicate of yarn.lock.
    assert conf["exclude_files"] == ["yarn.lock", "*.min.js", "node_modules/x.js"]
    # The rest of the profile survives intact.
    assert conf["max_code_tokens"] == 24000
    assert "You are CodePulse." in conf["prompt_vars"]["self_id"]


def test_write_run_profile_handles_profile_without_exclude(tmp_path):
    base = tmp_path / "p.toml"
    base.write_text("max_code_tokens = 100\n", encoding="utf-8")
    out = scope_gate.write_run_profile(base, tmp_path / "r", ["dist/a.js"])
    conf = tomllib.loads(out.read_text(encoding="utf-8"))
    assert conf["exclude_files"] == ["dist/a.js"]
    assert conf["max_code_tokens"] == 100


def test_write_run_profile_escapes_special_paths(tmp_path):
    base = _base_profile(tmp_path)
    out = scope_gate.write_run_profile(base, tmp_path / "r", ['weird "quoted"/back\\slash.js'])
    # Must still be valid TOML with the exact path preserved.
    conf = tomllib.loads(out.read_text(encoding="utf-8"))
    assert 'weird "quoted"/back\\slash.js' in conf["exclude_files"]


def test_apply_scope_gate_snapshot_rewrites_profile_env(tmp_path, monkeypatch):
    import codepulse_app.server as server

    monkeypatch.setattr(server, "RUNS_DIR", tmp_path / "runs")
    run_id = "20260725-140000-abcd1234"
    server.run_dir(run_id).mkdir(parents=True)

    repo = tmp_path / "repo"
    _write(repo, "app/server.py")
    _write(repo, "node_modules/dep/index.js")
    _write(repo, "yarn.lock", "lock\n")
    server.atomic_write_json(
        server.meta_path(run_id),
        {"id": run_id, "changed_files": ["app/server.py", "node_modules/dep/index.js", "yarn.lock"]},
    )

    env: dict[str, str] = {}
    payload = {"mode": "refs", "refs": snapshot.SNAPSHOT_REFS}
    server.apply_scope_gate(run_id, repo, payload, env)

    assert env["GITO_EXTRA_PROJECT_CONFIG"].endswith("review_profile.run.toml")
    conf = tomllib.loads(Path(env["GITO_EXTRA_PROJECT_CONFIG"]).read_text(encoding="utf-8"))
    assert "node_modules/dep/index.js" in conf["exclude_files"]
    meta = server.read_json(server.meta_path(run_id), {})
    assert meta["scope_gate"]["excluded_count"] == 2
    assert meta["scope_gate"]["kept_count"] == 1


def test_apply_scope_gate_leaves_normal_pr_untouched(tmp_path, monkeypatch):
    import codepulse_app.server as server

    monkeypatch.setattr(server, "RUNS_DIR", tmp_path / "runs")
    run_id = "20260725-141000-beef0001"
    server.run_dir(run_id).mkdir(parents=True)
    server.atomic_write_json(
        server.meta_path(run_id), {"id": run_id, "changed_files": ["yarn.lock"]}
    )

    env: dict[str, str] = {}
    server.apply_scope_gate(run_id, tmp_path, {"mode": "working"}, env)

    # A normal PR is never gated: env untouched, no scope_gate meta written.
    assert "GITO_EXTRA_PROJECT_CONFIG" not in env
    assert "scope_gate" not in server.read_json(server.meta_path(run_id), {})


def test_real_review_profile_round_trips():
    # The shipped profile must merge cleanly (it carries multi-line prompts).
    real = Path(__file__).resolve().parent.parent / "codepulse_app" / "review_profile.toml"
    import tempfile

    with tempfile.TemporaryDirectory() as d:
        out = scope_gate.write_run_profile(real, Path(d), ["node_modules/x.js"])
        conf = tomllib.loads(out.read_text(encoding="utf-8"))
    assert "node_modules/x.js" in conf["exclude_files"]
    # Baseline entries from the shipped profile are still present.
    assert "poetry.lock" in conf["exclude_files"]
    assert conf["prompt_vars"]["self_id"].strip().startswith("You are CodePulse")
