name: "Gito: React to GitHub comment"

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: read
  pull-requests: read
  reactions: write

jobs:
  process-comment:
    if: |
      github.event.issue.pull_request &&
      (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      ) &&
      (
        contains(github.event.comment.body, 'gito fix')
      )
    runs-on: ubuntu-latest

    steps:
    - name: Get PR details
      id: pr
      uses: actions/github-script@v7
      with:
        script: |
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          return {
            head_ref: pr.data.head.ref,
            head_sha: pr.data.head.sha,
            base_ref: pr.data.base.ref
          };

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ fromJson(steps.pr.outputs.result).head_sha }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with: { python-version: "3.13" }

    - name: Install Gito
      run: |
        pip install poetry
        poetry install
        echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
        # installation from PYPI:
        # pip install gito.bot~=2.0

    - name: Run Gito react
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LLM_API_TYPE: none
      run: |
        gito react-to-comment ${{ github.event.comment.id }}
