name: Print PR Comment

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  print-comment:
    # Only run on pull request comments
    if: github.event.issue.pull_request || github.event_name == 'pull_request_review_comment'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create Python script
      run: |
        cat > print_comment.py << 'EOF'
        import os
        import json
        
        def main():
            # Get the comment body from environment variable
            comment_body = os.environ.get('COMMENT_BODY', '')
            comment_author = os.environ.get('COMMENT_AUTHOR', '')
            pr_number = os.environ.get('PR_NUMBER', '')
            
            print("=" * 60)
            print(f"NEW PR COMMENT ON PR #{pr_number}")
            print("=" * 60)
            print(f"Author: {comment_author}")
            print(f"Comment:")
            print("-" * 40)
            print(comment_body)
            print("-" * 40)
            print("=" * 60)
        
        if __name__ == "__main__":
            main()
        EOF

    - name: Print PR comment
      env:
        COMMENT_BODY: ${{ github.event.comment.body || github.event.review_comment.body }}
        COMMENT_AUTHOR: ${{ github.event.comment.user.login || github.event.review_comment.user.login }}
        PR_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
      run: python print_comment.py